#!/usr/bin/bash
EXEFILE=123789.exe
rm -vf $EXEFILE
echo g++-12 --std=c++20 -o $EXEFILE  $1
g++-12 --std=c++20 -o $EXEFILE  $1
echo Please execute $EXEFILE
echo -----------------------------------------------------------
./$EXEFILE
echo -----------------------------------------------------------
