#! /usr/bin/bash
#  extension="${filename##*.}"
#  filename="${filename%.*}" 
#CPPFILE=$1
#FILENAME=${CPPFILE%.*}
#FILEEXT=${CPPFILE##*.}
FILEEXE=123789.exe
SRCFILES=$@
echo Link all objects file and bild
rm $FILEEXE
echo g++-12 --std=c++20 $SRCFILES -o $FILEEXE
     g++-12 --std=c++20 $SRCFILES -o $FILEEXE
echo please execute $FILEEXE ...
echo ------------------------------------------------
if [[ -f "$FILEEXE" ]]; then
  ./$FILEEXE
fi
echo ------------------------------------------------

