#! /usr/bin/bash
#  extension="${filename##*.}"
#  filename="${filename%.*}" 
# CPPFILE=$1
# FILENAME=${CPPFILE%.*}
# FILEEXT=${CPPFILE##*.}
FILEEXE=123789.exe
SRCFILES=$@
echo Compile cpp files "$SRCFILES"
rm $FILEEXE
echo g++-12 --std=c++17 -Wall -Wextra $SRCFILES -o $FILEEXE
g++-12 --std=c++17 -Wall -Wextra $SRCFILES -o $FILEEXE
echo please execute $FILEEXE ...
if [[ -f "$FILEEXE" ]]; then
  echo ------------------------------------------------
  ./$FILEEXE
  echo ------------------------------------------------
fi

